// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Book struct {
	ID     int64
	Title  string
	Author string
	Year   sql.NullInt64
}
